### PR TITLE
Decoupling CETEIcean and a few more changes. Version 2?

### PR DESCRIPTION
**Pull request by raffazizzi**
Hello! Thanks for putting together this great library. I have made a few changes, the main one being decoupling CETEIcean so this library can be used either with CETEIcean, or pre-generated prefixed documents (my use case), or even with other Custom Elements libraries. These changes break back compatibility so I upped the version to 2.0.0. It would be great to be able to use this library for my use case and publish a new version to NPM, instead of having to publish a fork. I hope you'll think this is a good idea! Below is a summary of changes with explanations and I'm happy to make further changes as needed.

* Added my name to the MIT license and removed the comment pointing to my original idea in https://github.com/raffazizzi/mermtt/. I hope this is an acceptable way of sharing code ownership!
* Decoupled CETEIcean. `TEIRender` now expects a DOM object instead of a path to a TEI file. CETEIcean can still be used, but it needs to be handled by the user. I added an example in `examples/ceteicean.js` and added a script to compile a working example.
* I added a component to handle TEI children and exposed it to the API, so that user-defined components can continue applying routes to nested elements (see readme for an example)
* Changed handling of the conflict between TEI attribute `ref` and React `ref`. Instead of prefixing it (`_ref`) I capitalize it (`Ref`). This allows it to go through the case sensitive processing, but gets rendered in the browser as the original lowercase `ref`. I think this is an innocent hack that is worth to maintain an isomorphic TEI in the browser.
* Updated readme with examples of use.
* Bumped to version 2 and adjusted dependencies (also updated to React 17)

### CODE REVIEW

**Comment by pfefferniels** [comment]
Hi Raffaele, Thanks for this pull request – I think these are great changes and I agree to everything you propose! I will merge and publish a new NPM version afterwards … :-)

**Comment by pfefferniels** [comment]
Version 2 is now published!

**Comment by raffazizzi** [comment]
Thank you! One more thing related to the published version: when I install it e.g. with `npm i react-teirouter@latest` I get version 2.0.0, but the code in `dist` seems to still be the old one (e.g.`TEIElement` is still in the scope and `TEINodes` is not). Perhaps the new code needed to be built before publishing? Perhaps it's possible to amend the current npm release, but no problem if this requires a bump to 2.0.1. Let me know if this is better handled as an issue.

**Comment by raffazizzi** [comment]
I also just noticed that I left a couple lines with the old API in the Readme. The examples with the user-defined `Reference` component now have:

```js
const target = props.teiDomElement.getAttribute('target')
```

but they should have:

```js
const target = props.teiNode.getAttribute('target')
```
Notice that this occurs in two examples. 

This shows up on npm too, so it would be good to fix it! But it's not as urgent as the other problem above.

**Comment by pfefferniels** [comment]
> Thank you! One more thing related to the published version: when I install it e.g. with `npm i react-teirouter@latest` I get version 2.0.0, but the code in `dist` seems to still be the old one (e.g.`TEIElement` is still in the scope and `TEINodes` is not). Perhaps the new code needed to be built before publishing? Perhaps it's possible to amend the current npm release, but no problem if this requires a bump to 2.0.1. Let me know if this is better handled as an issue.

Yes, I somehow forget the right procedure – I think it should work now (with 2.0.3) ...

**Pull request merged**
